### ISSUE TITLE
macho doesn't agree with `otool -l file`

### ISSUE THREAD

**Issue by fitzgen** [richo/macho-rs#1]
Hey Richo!

I'm writing a DWARF lib in rust and am trying to extend my [existing example program](https://github.com/fitzgen/gimli/blob/master/examples/dwarfdump.rs) from only Linux and ELF to also OSX and Mach-O.

I have this compiling just fine locally, however `macho` seems to end up missing sections/segments that should exist (at least according to `otool`).

I'm parsing like this:

``` rust
        let mut file = fs::File::open(path).expect("Could not open file");
        let mut buf = Vec::new();
        file.read_to_end(&mut buf).expect("Could not read file");

        let parsed = macho::MachHeader::parse(&buf[..]).expect("Could not parse macho-o file");
        println!("parsed = {:#?}", parsed);
```

Here is the `otool -l` vs `macho` output: https://gist.github.com/fitzgen/24a577cb65a1fbb9de92dc6e8a128071

Any idea what's up?

**Comment by fitzgen** [comment]
Here is the macho file in question: [objfile.zip](https://github.com/richo/macho-rs/files/379158/objfile.zip)

**Comment by richo** [comment]
Urgh, github notifications are the worst. I'll have a look at this tonight.

**Comment by richo** [comment]
If I had to guess it's likely that I've off by one'd something in the parser, I had a ton of those bugs while writing it.

**Comment by richo** [comment]
Having had a quick look I suspect it's because it's a companion file, not an executable and it's probably that I made some sweeping assumptions while writing it. I'm hoping to have a closer look soon, but I'm willing to bet that the bug is somewhere around here https://github.com/richo/macho-rs/blob/master/src/lib.rs#L60 where it's not correctly dealing with the load commands and just falling through. Debugging shouldn't be too hard- if you're still in the bay area I'd be down to pair next week?

**Comment by fitzgen** [comment]
I totally would, but I moved to Portland last year.

Anyways, for my program, I ended up using bindgen and wrapping the system mach-o library for now:

https://github.com/fitzgen/mach_o_sys
https://github.com/fitzgen/mach_o

Would love to switch over at some point in time, though, because the system lib has really poor docs and API...

**Comment by richo** [comment]
Aha! I spotted the bug finally. parsing is hard.

I'll get a patch out for this hopefully soon. No promises about what other issues you'll run into, but if you're still interested in migrating back please feel free to file more issues

**Comment by richo** [comment]
Ok I finally got you a fix!

With the code that's on master it now emits https://gist.github.com/7da37f7da9d03382f7459f1a910d76de

which should line up more with what you're expecting. I'll try to write a parser for LC_UUID and LC_SYMTAB which are the load commands your object has that aren't implemented, but at least the file structure parses correctly now.

**Comment by richo** [comment]
@fitzgen do you mind if I include your binary as a testcase?

**Comment by fitzgen** [comment]
Go for it!
